#pragma once

// From glfw3.h
#define ORNN_MOUSE_BUTTON_1         0
#define ORNN_MOUSE_BUTTON_2         1
#define ORNN_MOUSE_BUTTON_3         2
#define ORNN_MOUSE_BUTTON_4         3
#define ORNN_MOUSE_BUTTON_5         4
#define ORNN_MOUSE_BUTTON_6         5
#define ORNN_MOUSE_BUTTON_7         6
#define ORNN_MOUSE_BUTTON_8         7
#define ORNN_MOUSE_BUTTON_LAST      ORNN_MOUSE_BUTTON_8
#define ORNN_MOUSE_BUTTON_LEFT      ORNN_MOUSE_BUTTON_1
#define ORNN_MOUSE_BUTTON_RIGHT     ORNN_MOUSE_BUTTON_2
#define ORNN_MOUSE_BUTTON_MIDDLE    ORNN_MOUSE_BUTTON_3